#!/usr/bin/env bash

# Only functions that are used when setting up a fresh install

# Seek git author information
setup_git_author() {
    e_process "Setting up Git author"

    # Variables
    local GIT_AUTHOR_NAME="jodybrewster"
    local GIT_AUTHOR_EMAIL="jodybrewster@gmail.com"

    # set the credentials (modifies ${HOME}/.gitconfig)
    $(git config --global user.name "$GIT_AUTHOR_NAME")
    $(git config --global user.email "$GIT_AUTHOR_EMAIL")
    git config --global core.editor /usr/bin/vim

    e_success "Git author is $(git config user.name) <$(git config user.email)>"
}
